stages
    - build
    - job1
    - test
        - deploy

build:
  stage: build
  script:
	- echo "Check node version and build your binary or docker image."

job1:
  script: rspec
  coverage: '/Code coverage: /^\s*Lines:\s*\d+.\d+\%/'

test:
  stage: test
  script:
	- echo "Run your tests here."

deploy:
  stage: deploy
  script:
	- echo "Deploy your code ":
